### ISSUE TITLE
Bring back no-undefs in ESLint

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#101]
This requires commenting within each file the globals it uses.

In theory, we should namespace this stuff better, e.g. `Translator.updateLangList()` instead of just `updateLangList()`...

The rule is really useful so it would be nice to have back.

**Comment by unhammer** [comment]
Yeah, there's a bit of spaghetti some places :-) (re: #80 )

**Comment by sushain97** [comment]
Merge into #80
