### ISSUE TITLE
Back to top bottom

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#108]
Add a button to the bottom right that appears when it gets longer than X pixels that when pressed will bring the user to the top of the page and disappear.

**Comment by share-with-me** [comment]
@sushain, I have added this functionality. Find the demo in the video in this link.
[Demo Video For go-to top button](https://drive.google.com/open?id=0BwrSYlOsMCyWNEN5dmpGUXNjREk)

**Comment by sushain97** [comment]
@share-with-me Great work and demo! Switch the text to an icon (we use FontAwesome iirc) and try something out with opacities similar to https://codyhouse.co/gem/back-to-top/. It also can be hidden on mobile since we don't have dynamically extending input boxes.

Finally, send a PR! :) I'd like to see the code.

**Comment by share-with-me** [comment]
@sushain97 , I have changed the text to fa-icon. Also, used the same color as the 'a' links on the page. Tried stuff with opacity too. If this satisfies, I will go ahead and make a PR :D (Well after ensuring top-icon is hidden on mobile devices :P )
[Demo - up](https://drive.google.com/open?id=0BwrSYlOsMCyWMnBnUXJtX25tTXc)

**Comment by share-with-me** [comment]
@sushain97 , umm, I think we do have dynamically extending input boxes right? When I pasted large amount of data in input box, its length extended dynamically. So I do not understand why we do not need the go-top button on mobile devices?

**Comment by sushain97** [comment]
@share-with-me The dynamic text boxes are disabled on mobile devices.

I like the demo! Send a PR so I can try it out myself. I would suggest not hardcoding any colors but rather using one of the specific button classes that bootstrap provides if you don't want the default, .e.g. `btn-info`.

**Comment by share-with-me** [comment]
@sushain97 Awesome! I will get on it and disable the functionality on mobile devices.! (sorry for delay-had slept off :P)

**Comment by share-with-me** [comment]
Should I hide in tablet size devices too? (or only mobile devices)

**Comment by sushain97** [comment]
@share-with-me whichever sizes that the expanding is disabled. Check the code to find out. Should be straightforward.

**Comment by share-with-me** [comment]
@sushain97 , Done with the functionality. Here is the demo link.[https://drive.google.com/open?id=0BwrSYlOsMCyWVzFPbFNqOG5ZVTA](https://drive.google.com/open?id=0BwrSYlOsMCyWVzFPbFNqOG5ZVTA)
Create a PR.

**Comment by shrey1608** [comment]
Hello @sushain97 i have also made the top button according you told as a contibution and also as a part of gsoc coding challenge https://drive.google.com/file/d/1hnJHb4JlbJ1VdMYnHM_BrJrVAd-CoGDL/view?usp=sharing please have a look at it Thanks

**Comment by sushain97** [comment]
a) This issue is already closed (and solved). Please work on another issue.
b) Your screencap has nothing to do with html-tools.

**Comment by shrey1608** [comment]
okay @sushain i will do open issues. and i have made a simple model of
language detection. can you please have a look at it.
https://github.com/shrey1608/Language-Detection

**Comment by sushain97** [comment]
How much coverage of Apertium's languages does your repo have? Also, please submit any language detection work to the apertium-apy repository.

**Comment by shrey1608** [comment]
The coverage of the Apertium's languages in my repo are 33 out of 41. Okay
i will do the submission to the apertium-apy repo by today.

**Comment by shrey1608** [comment]
Hello again! can we use googletrans as the core for language detection?

**Comment by sushain97** [comment]
Not unless it's free and open-source software.

**Comment by shrey1608** [comment]
Hello Sushain
I have made a Draft of  gsoc proposal please have a look at it and provide
me suggestions.
http://wiki.apertium.org/wiki/User:Shrey1608
