### ISSUE TITLE
Locale Specific Index Page of Apertium

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#115]
In the current model, the build command first generates index.eng.html from localise-me.html and the index page is set to this. However, if I access this in some other region with a different locale, the index page should be of that locale! Perhaps we could add a field in config file which mentions the user locale (defaults to english) and then during build, we generate the appropriate home page for the user. This feature could be something similar to DEFAULT_MODE. After reading the description of various fields in config file, I could not infer if such a feature is already present.
![screen shot 2017-03-15 at 9 35 42 pm](https://cloud.githubusercontent.com/assets/8894636/23963873/af9a4672-09d8-11e7-8e53-a6e1a908d3b4.png)

**Comment by sushain97** [comment]
I think that the idea here might be to allow making the _default_ locale be customizable. i.e., for a website intended for users in Spain, the landing page would be Spanish even before refresh/dynamic localization based on the browser.

**Comment by share-with-me** [comment]
@unhammer I was not viewing it in private browsing mode and had cookies enabled. Therefore, I could not see. I set locale to spa and it took me to index.spa.html. Awesome :D . This is exactly what I wished.
However, as @sushain97 said, we could give a feature of making the index page local even before rendering the index.eng.html and waiting fir JS to load. 
![screen shot 2017-03-16 at 9 42 22 am](https://cloud.githubusercontent.com/assets/8894636/23981506/0fd1999c-0a2d-11e7-8402-85521867e199.png)

**Comment by unhammer** [comment]
@share-with-me could you try ac38feaf174b86c4838aa447a409a7e651b657d2 and see if that works?

**Comment by share-with-me** [comment]
Hey @unhammer Extremely sorry for sounding noob :P But how do I retreive a specific commit from a remote branch? (like yours in this case). I have checked this [link](http://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository) on Stackover flow but unable to fetch! I am a bit new to git in terms of majorly contributing to remotes :P 
I wish to test the commit locally. Thanks!

**Comment by unhammer** [comment]
oh this one's pushed to goavki master; if you don't have that as a remote already, just
`git remote add goavki https://github.com/goavki/apertium-html-tools/`
then e.g. from your master branch, `git pull goavki master`

**Comment by share-with-me** [comment]
@unhammer Awesome. That worked perfectly.  Now if I want to migrate these updates in all my local branches without affecting my commits in those branches, is it possible to do that? If so, how?

**Comment by unhammer** [comment]
If no one else has checked them out, I guess it's just `git fetch goavki` and `git rebase goavki/master` (when you're on that local branch)

**Comment by share-with-me** [comment]
@unhammer Thank you so much! This worked like charm! I have updated my local branches with the master branch (preserving my commits too). Thanks!
