### ISSUE TITLE
Different Modals open on clicking 'Help us Improve Apertium'

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#118]
Currently, on mobile, when we click on 'Help Us Improve Apertium', the `info` modal pops up. However, when we click the same on laptop/desktop, the `about` modal pops up. Is it deliberately done this way? If so, we can include the sourceforgenet mailto address in the `about` modal too perhaps? Also, opening the same modals seems a bit repetitive!
Following are screenshots:
![screen shot 2017-03-16 at 10 14 11 am](https://cloud.githubusercontent.com/assets/8894636/23982272/6d49fcd6-0a32-11e7-89f3-22b8869c2cc2.png)
![screenshot_20170316-095327](https://cloud.githubusercontent.com/assets/8894636/23982312/cd251ee2-0a32-11e7-9d2e-79f3519b249f.png)
![screen shot 2017-03-16 at 10 14 52 am](https://cloud.githubusercontent.com/assets/8894636/23982318/d3fd25e8-0a32-11e7-8de8-2bfe90a495fb.png)

**Comment by sushain97** [comment]
> Is it deliberately done this way?

Yes.

> If so, we can include the sourceforgenet mailto address in the about modal too perhaps?

It is linked through the "contact us" link.

> Also, opening the same modals seems a bit repetitive!

They're different as you reference.

**Comment by share-with-me** [comment]
@sushain97  Ohh Awesome. Yep, they are linked! I will close the issue.
