### ISSUE TITLE
Unable to run make command

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#121]
On running make, I get the following error on OS X El Capitan. Preliminary browsing yielded solutions like disabling the secure option of curl command. However, I believe it has something to do with the security certificate on host website. How to solve this error?

Edit: [This link](https://github.com/ContainerSolutions/minimesos/issues/440) made me feel it has to do something on host side.

![screen shot 2017-03-20 at 8 12 17 pm](https://cloud.githubusercontent.com/assets/8894636/24105154/0ac22af4-0daa-11e7-983e-9ef4676b769e.png)

**Comment by unhammer** [comment]
apertium.org's cert expired; some issue with the cron job :( I've notificed @ftyers

**Comment by share-with-me** [comment]
Ohh! I was worried for a sec that I screwed up by git commands and thereby some `make` issues :P. I will meanwhile keep on making local changes (to test) until we generate a new certificate :D

**Comment by sushain97** [comment]
Closing this issue since it's completely external to this repo.

@share-with-me you can circumvent this issue by using `http://turkic.apertium.org:8080` or running APy locally (http://wiki.apertium.org/wiki/Apertium-apy).
