### ISSUE TITLE
Type Error occurs when nothing selected

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#122]
Currently, in Analyser or Generator mode, if we do not select anything from dropdown and click on `Analyse`, a type error of being `undefined` occurs on the console. Should this be eliminated by keeping a check on whether the dropdown item is selected and then letting the analyse function progress else put a console warn?  Or is this unnecessary from application point of view? 
I tried to implement this functionality and following are the screenshots:

![screen shot 2017-03-22 at 4 23 36 pm](https://cloud.githubusercontent.com/assets/8894636/24194766/563274ac-0f1d-11e7-87ad-acab4187161e.png)
![screen shot 2017-03-22 at 4 24 26 pm](https://cloud.githubusercontent.com/assets/8894636/24194775/5e5a3656-0f1d-11e7-81f0-8b4f3ad03c54.png)

**Comment by sushain97** [comment]
Hm, I do want to prevent this error from occurring. However, there's no need for a console message. Send your PR and I'll take a look.

Thanks!

**Comment by share-with-me** [comment]
@sushain97 I have created a PR for the same. Please have a look. #123
