### ISSUE TITLE
400-Bad Request Error on 'Detect Language'

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#124]
Currently, when the `#originalText` div is empty and we run the `Detect Language` feature, we get a `400-Bad Request Error`. It says the request is improperly configured and not conforming to the structure expected by API. Is it because the data is empty? I tried by keeping a check that the function works only when data is non-empty. And it gets resolved. Is my approach for the this issue correct?

**Before**
![screen shot 2017-03-22 at 11 25 57 pm](https://cloud.githubusercontent.com/assets/8894636/24213131/74c4fd7e-0f57-11e7-8a00-6878acea451e.png)

**After**
![screen shot 2017-03-22 at 11 41 20 pm](https://cloud.githubusercontent.com/assets/8894636/24213610/1ad8e562-0f59-11e7-999e-87d6fe63a418.png)

**Comment by sushain97** [comment]
Preventing a request when the text is empty is probably wise. The console message is not necessary though.

Send a PR and I'll take a look. Thanks!

**Comment by share-with-me** [comment]
@sushain97 I have created a PR for this #125 . Please have a look.
Thanks

**Comment by share-with-me** [comment]
@sushain97  The PR has been merged. Should I close the issue?
