### ISSUE TITLE
500-Internal Server Error on TranslateDoc in localhost

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#126]
I am trying to use the feature `translateDoc` on my localhost but it gives a `500-Internal Server error` and I am unable to translate a text file. However, the same works perfectly when I access it on the apertium.org website. What might I be doing wrong? Is it something to do with `piwik.php` because I can see it loading via `GET` on apertium site but it does not reach that part on localhost. 
The `XMLHttpRequest() with POST` seems to work perfectly well on apertium site.
I am attaching the screenshots.

**Localhost**
![screen shot 2017-03-23 at 8 13 01 pm](https://cloud.githubusercontent.com/assets/8894636/24259660/8a7ed674-1017-11e7-8f35-d8ec12dccfd3.png)

**Apertium Website**
![screen shot 2017-03-23 at 8 13 54 pm](https://cloud.githubusercontent.com/assets/8894636/24259638/7bf106a4-1017-11e7-8806-83a374716097.png)

**Comment by unhammer** [comment]
what does apy say?

**Comment by share-with-me** [comment]
Do we need to setup apy locally for this feature on localhost? I have set `https://www.apertium.org/apy` as my server in `config` file and I believe all of the requests are going out this server only.  Currently, the console says the following : 

204 Error - No content
500 Error - Internal Server Error

![screen shot 2017-03-24 at 2 41 31 pm](https://cloud.githubusercontent.com/assets/8894636/24287646/6d8fd930-10a0-11e7-95ae-1f278d66ca8b.png)

**Comment by sushain97** [comment]
There could easily be a problem with the server. Use a local installation of APy. Debugging this is difficult otherwise. It's a POST so it could have something to do with CORS.

> Is it something to do with piwik.php because I can see it loading via GET on apertium site but it does not reach that part on localhost.

This isn't relevant.

**Comment by share-with-me** [comment]
> There could easily be a problem with the server. Use a local installation of APy. Debugging this is difficult otherwise. It's a POST so it could have something to do with CORS.

Yep, only issue being I was facing difficulties in setting up APy locally. Would try it again. 
Thanks :D

**Comment by sushain97** [comment]
Closing since it's almost certainly an APY version problem.
