### ISSUE TITLE
langdetect: target language button changes but not url-bar, gives "translation not available"

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#131]
```
<qdb> hello . https://www.apertium.org/ has some bug. i pasted kazakh text and
    target button changed to tatar, but, it said "translation is not
    available". then i see that it was written kaz-spa in address bar.  [20:42]
```

I can reproduce. Go to e.g.
https://www.apertium.org/index.eng.html?dir=eng-spa#translation
then paste in 

*орналасқан Шығыс Азиядағы мемлекет. Астанасы — Сеул. БАҚ өкілдерімен жиі қолданылатын, мемлекеттің бейресми атауы — Оңтүстік Корея.*

and click the "detect language" button. It switches to Kazakh on source and Tatar shows as the only choice on target, but the url field says "kaz-spa" and the translated-text field stays empty.

**Comment by share-with-me** [comment]
Looking at the code of `detectLanguage()`, it seems that only `curSrcLang` is determined in the `success` callback. A `curDstLang` update should also be made according to the `curSrcLang`; which isn't there (and this may be the cause I believe!) Thus, we have source as "kaz" but no where the code in the same callback updates the `destination language buttons` and so forth to have a "tat". I added `autoSelectDstLang()` to the `success` callback with a few modifications and it does give correct output now. However, I am under confident of my solution as I do not understand how I should test it (how do I understand if its working for different languages?)

**Comment by sushain97** [comment]
From @unhammer's bug report, it appears that

1. The destination language is being switched to `tat`.
2. The URL bar is not updated to `kaz-tat`.
3. A new translate request is not fired to update the target language text.

@share-with-me your description of the situation is not consistent with (1) above. Are we experiencing the same bug?

**Comment by share-with-me** [comment]
@sushain97 , um, when I do a `console.log` of the languages as I have shown in the below code, I get the output as in the image after that! The output shows that `curDstLang` is not updated to `tat`! I have made sure that `tat` does not appear in my `recentDstLangs` too. That can be seen in the `console` output. Thus, I believe my observation is not exactly same as the one reported in @unhammer 's report!
@unhammer , could you please correct me if I am unable to find out the snippet wherein the `curDstLang` gets updated as per the detected language?

**Success callback in detectLanguage()**

```
        success: function (data) {
            var possibleLanguages = [];
            for(var lang in data) {
                possibleLanguages.push([lang.indexOf('-') !== -1 ? lang.split('-')[0] : lang, data[lang]]);
            }
            possibleLanguages.sort(function (a, b) {
                return b[1] - a[1];
            });

            var oldSrcLangs = recentSrcLangs;
            recentSrcLangs = [];
            for(var i = 0; i < possibleLanguages.length; i++) {
                if(recentSrcLangs.length < TRANSLATION_LIST_BUTTONS && possibleLanguages[i][0] in pairs) {
                    recentSrcLangs.push(possibleLanguages[i][0]);
                }
            }
            recentSrcLangs = recentSrcLangs.concat(oldSrcLangs);
            if(recentSrcLangs.length > TRANSLATION_LIST_BUTTONS) {
                recentSrcLangs = recentSrcLangs.slice(0, TRANSLATION_LIST_BUTTONS);
            }

            curSrcLang = recentSrcLangs[0];
            $('#srcLangSelect').val(curSrcLang);
            muteLanguages();

            $('#detectedText').parent('.srcLang').attr('data-code', curSrcLang);
            refreshLangList();
            $('#detectedText').show();
            $('#detectText').hide();
            for(var i = 0; i < recentDstLangs.length; i++) {
                console.log('Recent Language in callback: ' + recentDstLangs[i]);
            }
            console.log('After language detected' + curSrcLang + '-' + curDstLang);
        }
```

**Output**
![screenshot from 2017-07-05 19-26-43](https://user-images.githubusercontent.com/8894636/27867637-ea0bcb32-61b7-11e7-975f-aeb11145371a.png)

**Comment by share-with-me** [comment]
@sushain97 , @unhammer , one more issue that I see is in the following code snippet: `textTranslateRequest()` is fired up before `detectLanguage()` is completed! Shouldn't it be fired up once we know `detectLanguage()` is completed?! Following image shows it. `kaz` should be the `curSrcLang` when the `translateText()` is required?

```
        $('#detect').click(function () {
            $('.srcLang').removeClass('active');
            $(this).addClass('active');
            
            detectLanguage();
            textTranslateRequest();
            console.log('This is after detectLanguage() ends: ' + curSrcLang + '-' + curDstLang);
        });
```

**Output**
![screenshot from 2017-07-05 19-39-45](https://user-images.githubusercontent.com/8894636/27868270-dadbae46-61b9-11e7-8acd-ae9b619f3f4f.png)

**Comment by sushain97** [comment]
> Shouldn't it be fired up once we know detectLanguage() is completed?!

Yes.

> Wouldn't it make sense to move translateText() to the end of success callback in the detectLanguage() so that it is called only when we have both the languages?

No. I don't know where else `detectLanguage` is being called. Instead, give it a `callback` parameter and call callback at the end of its ajax request if it is truthy.
