### ISSUE TITLE
Switch to a store library

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#137]
Something like https://github.com/marcuswestin/store.js would render our `store.js` unnecessary and be a well-supported, more compatible solution.

Thoughts, @unhammer ?

It's 17.1 KB for the version with plugins (we don't need any) and 13 KB without (https://github.com/marcuswestin/store.js/blob/master/dist/store.legacy.min.js).

**Comment by unhammer** [comment]
Hm, our store.js is 926 *bytes* minified (when I paste it into https://duckduckgo.com/?q=minify+js+online&t=canonical&ia=answer). 

The problem we've had so far is detecting whether localStorage is supported by the browser or not – can we just copy that part? I don't feel having localStorage support is important enough for apertium.org's functionality that we should polyfill for old browsers (translation etc. should work just fine without localstorage). 

(I also don't like the API which lets you `get` without providing a fallback, but I realise that's a bit of a personal preference :-))
