### ISSUE TITLE
q=input+text

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#14]
It'd be cool if the contents of the q parameter were put into the input text box. 

I'm not 100 % sure if we should do like google and update it in the URL (gets a bit ugly for large texts, maybe only for small ones?)

**Comment by sushain97** [comment]
A little experimenting shows Google stores up to 1300 chars in the URL, probably due to limitations in the size of GET requests. We can do the same. They do not however as we do store the text in LocalStorage.

Thoughts?

**Comment by unhammer** [comment]
I like having it in localStorage, think we should keep doing that. 

I guess people look less and less at URL's these days (many browsers now hide the non-domain part to avoid some scam methods).

**Comment by sushain97** [comment]
We could do the URL in addition to LocalStorage. I can see a good number of people sharing translations via URL.

**Comment by jonorthwash** [comment]
Yeah, that seems reasonable to me too.  Having short translations hotlinkable would be cool.  When would it update the url, though?  As the source text is being entered, when focus is lost on input, after the translation is performed, ... ?

**Comment by sushain97** [comment]
It would make sense to update the URL whenever a translation is performed, this would be equivalent to loss of focus and our current system of x seconds of keyboard inactivity.

**Comment by jonorthwash** [comment]
But that's only the case if instant translation is selected.  What if it's not?

**Comment by sushain97** [comment]
Monitor just loss of focus and inactivity? Basically, maintain the timer either way but always update and only translate if instant is selected.

**Comment by jonorthwash** [comment]
Seems reasonable enough.

**Comment by svineet** [comment]
I am working on this, but it does not seem to be possible. Changing `window.location.href` triggers a refresh automatically. What google translate does it that it changes the `#part` to the query string but we are already using that part for modes (`#translation`). 

Maybe we should add a permalink button beside instant translation, that adds a q parameter to the url and on load the page respects the q get parameter. What say?

**Comment by xavivars** [comment]
@svineet, it can be done but not by direcctly changing `window.location.href`.

You need to use `window.history.state` in order to change the URL without refreshing.

More info (it can be a bit outdated, as the link is pretty old):  http://spoiledmilk.com/blog/html5-changing-the-browser-url-without-refreshing-page/

**Comment by sushain97** [comment]
@svineet, exactly what @xavivars said. See https://github.com/goavki/apertium-html-tools/blob/master/assets/js/persistence.js.

**Comment by svineet** [comment]
okay I used `replaceState`, thanks @xavivars and @sushain97.
