### ISSUE TITLE
Display APy endpoint being used in Sandbox

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#147]

**Comment by share-with-me** [comment]
@sushain97 , do you mean something like the following? Either `localhost` or the `apertium.org/apy`? Or We could append the `/perWord` example to the endpoint and then render the example based on the endpoint the user is hitting?

![screenshot from 2017-08-12 13-37-35](https://user-images.githubusercontent.com/8894636/29239131-74e8c64c-7f63-11e7-8ac2-297af30c1630.png)

**Comment by share-with-me** [comment]
Mistakenly closed it. Sorry!

**Comment by sushain97** [comment]
No, the example is supposed to indicate how an input would look. It
shouldn't include the API base URL. I'm also not a huge fan of randomly
placing the URL below the example.

**Comment by share-with-me** [comment]
>  I'm also not a huge fan of randomly placing the URL below the example.

What would be an appropriate position?

**Comment by sushain97** [comment]
I'm not sure. Part of issue is to find a nice place.

**Comment by share-with-me** [comment]
How does this look?

![screenshot from 2017-08-15 00-54-48](https://user-images.githubusercontent.com/8894636/29287977-b94eb75e-8154-11e7-8049-5a394712a62f.png)

**Comment by sushain97** [comment]
Looks better! Perhaps without the colon and fix the stylization of "APY" ->
"APy" at the same time.


[image: Sushain Cherivirala]
*Sushain K. Cherivirala *
Carnegie Mellon University, B.S. in Computer Science '17
Forward Deployed Software Engineer Intern, Palantir Technologies
Vice Chair, Undergraduate Student Senate
Research Assistant, Institute for Software Research
(713) 992-4043  <713-992-4043>| www.skc.name
