### ISSUE TITLE
Module extraction

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#15]
from http://www.google-melange.com/gci/task/view/google/gci2013/5827136816414720

> This point of this task is to merge the non-overlapping code [simple-html](http://svn.code.sf.net/p/apertium/svn/trunk/apertium-tools/simple-html/) and apertium-html-tools and make simple-html automatically extractable from html-tools.  That is, merge functionality from simple-html that doesn't exist in apertium-html-tools (language detection and anything else your mentors are aware of), and figure out a way to automatically extract just the translation part (or even better, each individual part) of apertium-html-tools to produce a distribution-ready simple-html interface.

**Comment by unhammer** [comment]
lang.detection is already there in html-tools?

**Comment by jonorthwash** [comment]
Yeah, the originally worded task was for GCI2013, so there have been changes since then that will have to be taken into account.

**Comment by sushain97** [comment]
Merge into #80.
