### ISSUE TITLE
Autoselect of destination language when option is changed on small screen is lacking

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#170]
Currently, in smaller screens window (zoomed at >= 200%), when a `select` option is changed in `srcLangSelect`, it does not automatically detect a corresponding destination language (which exists in the `pairs` of selected language).

For instance:

In the below image, I choose a language pair: `{eng: glg}`

![screenshot from 2017-07-22 13-18-20](https://user-images.githubusercontent.com/8894636/28489366-5be67588-6ee0-11e7-8bec-a1d12b5e50c8.png)

On changing the source language from dropdown to Hindi, the destination language still shows only `Galician` 

![screenshot from 2017-07-22 13-18-32](https://user-images.githubusercontent.com/8894636/28489379-919cfae4-6ee0-11e7-821e-6aef5c55e107.png)

It should detect the corresponding language (which is `Urdu`) and set the `dstLangSelect` to that value.

**Comment by share-with-me** [comment]
One more concern I have with respect the correct behaviour is the following screnario:

Eg, I choose `Breton` as my source and `French` as my destination. However, when I swap, I can see that `Breton` does not appear in the destination languages for `French`. In this case, should the code automatically detect one valid language for `French` (which in this case could be `spa`) from the destination pairs or leave the field as is displaying : `Translation Not Available`?? (since `{fra: bre}` language pair does not exist?)

What would be correct behavior? @sushain97 ?

**Comment by sushain97** [comment]
> It should detect the corresponding language (which is Urdu) and set the dstLangSelect to that value.

Is this the same behavior we have on the larger interface? If so, yes.

> What would be correct behavior? @sushain97 ?

Hm, I actually am not a fan of the switch button not actually switching. It would be strange UX.

**Comment by share-with-me** [comment]
> Is this the same behavior we have on the larger interface? If so, yes.

Yes. That is how it is on the larger interface.

> Hm, I actually am not a fan of the switch button not actually switching. It would be strange UX. I would rather end up with disabled options being selected.

Awesome. I would change accordingly.
