### ISSUE TITLE
Disable 'detectLanguage' when on 'docTranslation' interface?

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#174]
When on `docTranslation` interface, on clicking `detect`, it takes up the contents of `originalText` and does the detect. But, one would expect the functionality to detect the language of the contents inside the uploaded doc thereby making it misleading. **Does the `detectLanguage` functionality work for docs too?**
(I could only see the functionality for `translateText` interface).

If no, would it make sense to disable the `detect` button while on `docTranslation` interface and then enable it again while switching to `translateText` interface?

**Comment by unhammer** [comment]
It does not work for docs no, so disabling makes sense
