### ISSUE TITLE
Make the subtitle display "correctly" in RTL localisations.

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#18]
Compare subtitle ("Turkic") placement in the following screenshots.  Make RTL languages behave better than they are currently, and look close to as nice as LTR languages:

![screenshot_2015-08-21_010609](https://cloud.githubusercontent.com/assets/963849/9401665/f16a1466-47a0-11e5-8097-84b472cd07f3.png)

![screenshot_2015-08-21_010525](https://cloud.githubusercontent.com/assets/963849/9401666/f51405b8-47a0-11e5-9207-0e5b474d095b.png)

**Comment by sushain97** [comment]
@jonorthwash, could you update Turkic and see if this issue persists?

**Comment by jonorthwash** [comment]
Seems to be behaving more nicely :)

**Comment by jonorthwash** [comment]
I'm not sure if this is the ideal behaviour.  The "Turkic" part is on the wrong side of "Apertium", I'd say.
![screenshot_2016-01-06_140536](https://cloud.githubusercontent.com/assets/963849/12151742/a4f81196-b47e-11e5-9f94-ed7de2db44ad.png)

**Comment by imakhil25** [comment]
can you help me find the exact file path to that turkic file where it shows that way as it's in the image you have uploaded because it found that  it looks fine at  turkic.apertium.org  @jonorthwash

**Comment by jonorthwash** [comment]
https://github.com/goavki/apertium-html-tools/blob/master/index.html.in#L89
