### ISSUE TITLE
APY Sandbox request to use callApy method

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#183]
APY Sandbox request must use `callApy` method to make use of `GET` or `POST` as appropriate. However, a question I have here is, we send the contents of `sandboxInput` as a part of `url` in the request (and not the `data`). Thus, even with using `POST`, it gives a 414-Request URI too large error. Searching the web yielded that the contents should be part of `data` in the packet and not the url. Is this conceptually correct?

**Comment by sushain97** [comment]
Yes.

**Comment by share-with-me** [comment]
In that case, is there a way to not obtain 414 error for this request?

**Comment by sushain97** [comment]
Change APy to accept POST requests?

**Comment by share-with-me** [comment]
Currently, APy does accept POST requests based on the length of the request URL. However, for that, the `data` parameter holds the request values. In the Sandbox request, we do not have a `data` param. Instead, we directly send it appending to the URL. I tried POST in the scenario where all the data is appended to `url` param. However, even POST in that case gives a 414 error.

The following AJAX request with POST method too, gives a 414 - request URI too large error.

```
    currentSandboxRequest = $.ajax({
        **url: config.APY_URL + $('#sandboxInput').val(),**
        type: 'POST',
        beforeSend: ajaxSend,
        success: function (data) {
            $('#sandboxOutput').text(JSON.stringify(data, undefined, 3)).removeClass('blurred');
        },
        error: function (xOptions, error) {
            $('#sandboxOutput').text(error).removeClass('blurred');
        },
        complete: function () {
            ajaxComplete();
            $('#time').text(new Date().getTime() - startTime + ' ms');
            currentSandboxRequest = undefined;
        }
    });
```

**Comment by sushain97** [comment]
> In the Sandbox request, we do not have a data param.

Extract the URL params out of the value and put them into the `data`? I'm with this being a `wontfix` though...

**Comment by share-with-me** [comment]
> I'm with this being a wontfix though...

Should I drop it then? :P. I was just curious about it.

**Comment by sushain97** [comment]
Up to you!

**Comment by share-with-me** [comment]
Haha.. Closing it here :D
