### ISSUE TITLE
Clear apyRequestTimeout in the event of request abort

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#185]
In case of successive calls of the same AJAX method, the prior ones are aborted and only the last one gets executed. However, the prior requests do start the `apyRequestTimeout` timer in the `callApy` method and when aborted, cause this `apyRequestTimeout` variable to display the installation notification.

For instance, when `detectLanguage` is called successively (See console) , the first request is aborted. However, as the `apyRequestTimeout` variable which is set by this request is not cleared, it displays the notification erroneously.

![screenshot from 2017-08-15 00-45-03](https://user-images.githubusercontent.com/8894636/29287432-06ba68b4-8153-11e7-9f2f-d5d3f69e7cb7.png)

**Comment by sushain97** [comment]
Yeah, I experienced this problem :( Would appreciate a fix.

**Comment by share-with-me** [comment]
On it :D
