### ISSUE TITLE
dropdown improvements for RTL localisations

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#19]
Compare the following language dropdowns for RTL and LTR localisations.  The scrollbar in the RTL dropdown covers the first few (or last few) letters of each language name, and yet there's a bit space on the opposite side.  It's as if there is a padding setting, but it's on the wrong side?  Also, there's some issue with left- and right-aligning all the language names (depending on the currently localisation), but I think the current solution works and looks good, even if it's not technically "right".

![screenshot_2015-08-21_010801](https://cloud.githubusercontent.com/assets/963849/9401684/33cbf45a-47a1-11e5-80ce-16b4377feb0d.png)

![screenshot_2015-08-21_010824](https://cloud.githubusercontent.com/assets/963849/9401681/30a41f64-47a1-11e5-8f91-263bc36d18c9.png)

**Comment by jonorthwash** [comment]
Actually, the issue seems to be more complicated than this.  If a RTL localisation is the one the page loads on by default, then those dropdowns display correctly (with scrollbar on the left and not covering anything on the right, and no weird extra padding).  If it's then switched to a LTR localisation *without reloading the page* then the LTR dropdown has the same problem originally reported, but flipped from side-to-side.

Might this be a bug in my slightly outdated version of chrome?

**Comment by sushain97** [comment]
I feel like I have experienced this exact behavior before and narrowed it down to Chrome behaving badly.

**Comment by sushain97** [comment]
I think that this has been fixed in Chrome:

![](https://l.skc.name/cbwic)

I'm running 47.0.2526.106 (Official Build) m (64-bit) with Blink 537.36. Please verify whether it's still an issue for you.

**Comment by jonorthwash** [comment]
![screenshot_2016-01-05_135109](https://cloud.githubusercontent.com/assets/963849/12124419/712166cc-b3b3-11e5-87e9-fd3828417034.png)

I need to look into the status of that constant-sending-of-voice-data issue before I update chromium.

**Comment by jonorthwash** [comment]
Also, is there any way to get ltr languages on the left and rtl languages on the right, regardless of what the localisation is and which side the scrollbar is on?

**Comment by sushain97** [comment]
Should be fixed with cce47f522221f2f3fff0e2ffc6b1dc13394f43e7.

**Comment by jonorthwash** [comment]
Works for me in now-upgraded version of chromium, as well as whatever version of iceweasel I have.  I think it may have introduced some new bugs in iceweasel though?

![screenshot_2016-01-06_140128](https://cloud.githubusercontent.com/assets/963849/12151611/0abf6692-b47e-11e5-887d-fe19b99dec85.png)

**Comment by sushain97** [comment]
going to close this as a dup of #127 even though this came first since there's more discussion there.
