### ISSUE TITLE
perWord example on APy Sandbox page fails

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#196]
The example provided fails with a bad request error.  I am running this in my local instance of APy. 

![screenshot from 2017-08-20 16-08-44](https://user-images.githubusercontent.com/8894636/29494173-e0e1f09a-8593-11e7-85c1-69bf4a965585.png)

Edit: It fails for `https://www.apertium.org/apy` too.

![screenshot from 2017-08-20 16-15-25](https://user-images.githubusercontent.com/8894636/29494214-c9a8ae4a-8594-11e7-9489-321a4be150a9.png)

**Comment by share-with-me** [comment]
I changed the `lang=en-es` to `lang=eng-spa` and it worked. I am not sure what is going wrong here in the original example.

![screenshot from 2017-08-20 16-11-09](https://user-images.githubusercontent.com/8894636/29494188-33dfcdee-8594-11e7-9265-213e459d7329.png)

**Comment by sushain97** [comment]
This isn't an html-tools bug, it's an [APy](https://github.com/goavki/apertium-apy) problem. You may want to migrate your ticket over there.
