### ISSUE TITLE
localisation instructions should reference github, not subversion

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#20]
Update [localisation instructions](http://wiki.apertium.org/wiki/Apertium-html-tools#Localisation) to reference github instead of sourceforge's subversion.

**Comment by svineet** [comment]
this has been fixed

**Comment by jonorthwash** [comment]
The progresstable.sh link still points to svn.

**Comment by jonorthwash** [comment]
Also this page: http://wiki.apertium.org/wiki/Apertium-html-tools/Localisation

**Comment by jonorthwash** [comment]
Was this supposed to say 2017?
http://wiki.apertium.org/w/index.php?title=Apertium-html-tools&diff=61161&oldid=55864
