### ISSUE TITLE
theming issues, eternal wait with no time-out

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#206]
When I load apertium.org now, I get the following.  With the different resolutions I'm demonstrating that it doesn't seem to be window size that causes the bad position of the dropdown.

![2017-08-24-01 22 25_001](https://user-images.githubusercontent.com/963849/29650776-058d8948-886b-11e7-881a-284a480dfa1d.png)

![2017-08-24-01 22 38_001](https://user-images.githubusercontent.com/963849/29650772-01a13c1c-886b-11e7-87ed-57127b47df1c.png)

**Comment by sushain97** [comment]
APy is down:

https://www.apertium.org/apy/listPairs

Would not expect anything to work.
