### ISSUE TITLE
URL rewrite ignores path

### ISSUE THREAD

**Issue by flammie** [goavki/apertium-html-tools#21]
When opening http://flammie.dyndns.org/apy/ the URL gets rewritten to http://flammie.dyndns.org/index.???.html, which do not exist currently. URL in config.conf does include the path part like so:
```
HTML_URL = http://flammie.dyndns.org/apy/
```

**Comment by sushain97** [comment]
@flammie Try out the fix and let me know how it works :smile:

**Comment by flammie** [comment]
Seems to work for me now.
