### ISSUE TITLE
Split CSS into multiple files

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#212]
Our CSS would be better organized in multiple files based on the current comments indicating what function each part of it serves.

**Comment by idealadarsh** [comment]
@sushain97 I want to work on this and rearrange as well as fix the issues came up after my last PR.

**Comment by idealadarsh** [comment]
@sushain97 @shardulc I just completed the setup of apertium-html-tools. I now understand what you want, I'll remove inline styles, split the css files and also check its workability.
Are you guys available on IRC ( just in case  I needed to ask something ), if yes what's the approximate time peroid you guys are active on IRC or any other social network.

**Comment by sushain97** [comment]
@idealadarsh sounds good to me! You don't have to redo any work. The `inline-styles` branch is a good place to start. We are both available on IRC. I'm in EST and I believe @shardulc is PST (US timezones).

**Comment by diogoscf** [comment]
There is a single css rule-set labeled as analysis. Should I create a stylesheet just for that or should I add it to another stylesheet (like general)?

**Comment by sushain97** [comment]
Another stylesheet is fine.

On Dec 19, 2017 10:33 AM, "Diogo Fernandes" <notifications@github.com>
wrote:

There is a single css rule-set labeled as analysis. Should I create a
stylesheet just for that or should I add it to another stylesheet (like
general)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/issues/212#issuecomment-352793770>,
or mute the thread
