### ISSUE TITLE
Sort localisation languages in GUI

### ISSUE THREAD

**Issue by havet** [goavki/apertium-html-tools#23]
I noticed that the list of localisation languages locales.json is used
"as is" in the drop down list.  It would be more user friendly if it was sorted.

I suppose this would be a minor change in localization.js, but
unfortunately I've never learnt javascript. I got confused looking at
the code. I'd better not touch it.

**Comment by sushain97** [comment]
> Optional. Specifies a function that defines the sort order. If omitted, the array is sorted according to each character's Unicode code point value, according to the string conversion of each element.

I don't think that the natural sorting in JS of this particular set of language names would be particularly meaningful since many fall in different sections of the Unicode standard. Perhaps we would be best off defining a particular order we would prefer them to be in and setting that order.

**Comment by jonorthwash** [comment]
My impression at one point was that we were [manually] sorting it in English-alphabetical order of ISO code, but it would be good to decide on a standard and go with it.

**Comment by sushain97** [comment]
What do you think:

![image](https://cloud.githubusercontent.com/assets/4211838/15912097/5bd5caa8-2d87-11e6-9e2f-da83bf81d4e5.png)

![image](https://cloud.githubusercontent.com/assets/4211838/15912128/85bce59a-2d87-11e6-9338-f6fc74ade365.png)

**Comment by jonorthwash** [comment]
Those seem to be just unicode sorted by name?

**Comment by sushain97** [comment]
'sorted by name' is a tad bit ambiguous in this context :P

**Comment by jonorthwash** [comment]
The native name that's displayed, I mean

**Comment by sushain97** [comment]
@jonorthwash better?

**Comment by jonorthwash** [comment]
Uhh, I didn't file this bug, and didn't mind manually sorting it, since I was the one deciding how it got manually sorted most of the time :-P

**Comment by sushain97** [comment]
This should give us the ordering you said looked good on IRC! Mostly wanted you to verify how it looked on Turcik :)

**Comment by jonorthwash** [comment]
It seems to sort as expected on [turkic.apertium.org](http://turkic.apertium.org).  @havet, what do you think?

**Comment by jonorthwash** [comment]
So wait, it's unicode-sorted by native name now?

**Comment by sushain97** [comment]
Yes.

**Comment by jonorthwash** [comment]
Fair enough.
