### ISSUE TITLE
Buggy UI after switching into translate document/webpage after detecting language 

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#236]
No language is selected anymore:

![image](https://user-images.githubusercontent.com/4211838/34185880-097ea8ec-e4f6-11e7-948a-e7e60f9199bf.png)

**Comment by JPJPJPOPOP** [comment]
@sushain97 

We should probably just switch to highlighting the first language right since clicking detect-language automatically changes the first listed language to the detected one?

**Comment by sushain97** [comment]
Yes and yes.

**Comment by JPJPJPOPOP** [comment]
@sushain97 

Then I'm going to try working on this for my GCI task: https://codein.withgoogle.com/dashboard/task-instances/6122118573981696/

**Comment by sushain97** [comment]
@JPJPJPOPOP sounds good! Depending on how complex it ends up being, it may warrant an extra issue for the task.

**Comment by JPJPJPOPOP** [comment]
@sushain97 
Seems fair :D

**Comment by JPJPJPOPOP** [comment]
@sushain97 I'll do another one 👍 .
