### ISSUE TITLE
Change in language not taking effect immediately

### ISSUE THREAD

**Issue by Putti** [goavki/apertium-html-tools#24]
The string "Translation not yet available!" (in the target language's output box) doesn't change immediately to another language when changing the site's language. In order to change the string to another language you need to change the source language text input or change the translation pair etc.

**Comment by svineet** [comment]
How to reproduce:
* Type something and switch source language such that the destination language selected before is not supported for the source language now selected. "Translation not yet available" is shown.
* From the select box on the top right select some random language.
* Translation not yet available will not change, but on clicking translate again it will change to newly selected language. This change should happen instantly instead.

Had trouble reproducing so just putting this out there. Sorry if redundant.

**Comment by sushain97** [comment]
At first glance, this looks like it will *always* make the text in the translated text box the "Not Available" text, even when there is a translation available. Did you test it?
