### ISSUE TITLE
apy / identifyLang returns code 400

### ISSUE THREAD

**Issue by Androbin** [goavki/apertium-html-tools#240]
The "Detect Language" feature is broken due to a failing request:
![screenshot](https://user-images.githubusercontent.com/16437156/34388648-3584f636-eb35-11e7-8640-9971ad804ca2.png)

**Comment by sushain97** [comment]
This isn't an `html-tools` issue unless it doesn't we don't meet the spec for `/identifyLang`. It would be an `APy` issue.

**Comment by Androbin** [comment]
Sorry, the query string looked suspicious.

**Comment by sushain97** [comment]
Which part? It looks normal to me. Maybe the problem is that we're allowing lang identification on an empty string (APy shouldn't break on it but we also shouldn't allow it). Feel free to check and create a new (more specific) issue.
