### ISSUE TITLE
Detect Language fails for empty text

### ISSUE THREAD

**Issue by Androbin** [goavki/apertium-html-tools#241]
The interface doesn't catch attempts to detect the language of empty text which results in https://www.apertium.orf/apy/identifyLang producing code 400 errors.

![screenshot](https://user-images.githubusercontent.com/16437156/34388874-8c768274-eb36-11e7-86a6-3fa65eced2ef.png)

**Comment by sushain97** [comment]
I think the button should just be disabled.

**Comment by Androbin** [comment]
Quick clarification: when there is no text? or in general?

**Comment by sushain97** [comment]
> when there is no text?

This! Why would we always disable detection? :)
