### ISSUE TITLE
"Translation not yet available" when simply no target language selected

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#38]
don't know if this is would/should be fixed by the auto-select target language changes

**Comment by sushain97** [comment]
@unhammer does this look fixed to you?

**Comment by unhammer** [comment]
Probably; I tried `localStorage.clear()` on  https://apertium.org/ and then changed the url back to https://apertium.org/ (to avoid setting `?dir`); I couldn't reproduce it.
