### ISSUE TITLE
include hash of CDN scripts (jquery, bootstrap)

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#50]
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity 
seems simple enough

**Comment by TinoDidriksen** [comment]
What I found is that it'll completely break in some browsers. I used the default Bootstrap CDN tags with integrity, and it just wouldn't load correctly or consistently, so gave up on integrity. If you do enable, be sure to test in all relevant browsers.

**Comment by sushain97** [comment]
+1

--
Sushain K. Cherivirala
www.skc.name

**Comment by sushain97** [comment]
Was this ever tested on multiple browsers as @TinoDidriksen mentioned?

**Comment by share-with-me** [comment]
@sushain97 , what browsers and versions are we targeting? A list of them could be IE, Edge, Firefox, Chrome, Opera. I can test if the scripts run consistently across all of them. Locally, it works for me perfectly on chrome, firefox and safari. Will have to test them across the remaining ones. Just a simple local running on these browsers to check if the scripts are running perfectly would suffice?

**Comment by sushain97** [comment]
@share-with-me that sounds like a decent list and test. I wonder if there's a way to automatically test these through Travis (added #116).

**Comment by share-with-me** [comment]
@sushain97 Awesome. Meanwhile, I will find some ways of testing this. And first and foremost, get used to Hound and Travis-CI :P

**Comment by sushain97** [comment]
Closing since they were added and the ticket has now drifted to testing.
