### ISSUE TITLE
q= removes newlines

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#59]
try putting

```
a
b
c
```

into the text field; the URL goes q=abc, should probably urlencode (or whatever it's called) those newlines into %-something

**Comment by raj550** [comment]
I would like to take up the bug and fix it.

**Comment by share-with-me** [comment]
Is this issue still open? I cloned the repo locally and checked that the encoding works correctly (screenshots below). However, when I checked the website, it doesn't work. (Some merges not merged perhaps? But then , the cloned repo wouldn't have worked either). I checked the js files and found that the encodeURIComponent() function works correctly. (ss below)
![encodejs](https://cloud.githubusercontent.com/assets/8894636/23829883/c26a5368-0722-11e7-92cf-932a1ff6106a.png)

![newline_encoded](https://cloud.githubusercontent.com/assets/8894636/23829859/46ac49ac-0722-11e7-9b55-90ac1203ccca.png)
![space_encoded](https://cloud.githubusercontent.com/assets/8894636/23829862/4db50fea-0722-11e7-875e-119b8128b782.png)

**Comment by raj550** [comment]
@share-with-me You are right. It encoding works correctly in the local clone of repo. The issue may be with merging, thereby causing problems with the website.

**Comment by sushain97** [comment]
It appears that both of you are correct! This bug has been remedied at some point but the issue remained open, unfortunately. My apologies for this.

On the other hand, great work getting everything set up and running on your machines! Feel free to try your hand at one of the other issues!

**Comment by share-with-me** [comment]
@sushain97 Awesome! We will get on with other issues then!

**Comment by sushain97** [comment]
@share-with-me Sounds good! Feel free to also find your own defects/improvements based on comparing with other similar tools, e.g. Google Translate and/or exploring.

**Comment by share-with-me** [comment]
@sushain97 on it!
