### ISSUE TITLE
sometimes empty output box in epiphany-browser, firefox

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#60]
```
sudo apt-get install epiphany-browser
epiphany https://apertium.org
```

sometimes but not always, I get no output in the output box, even though the translation request is obviously sent and received.
[out.zip](https://github.com/goavki/apertium-html-tools/files/304668/out.zip)

**Comment by unhammer** [comment]
I'm now seeing this in Firefox too. If I open dev console, the /translate response has the full translated text, so this is definitely on the JS side.

**Comment by sushain97** [comment]
I can't duplicate this :( 

![image](https://cloud.githubusercontent.com/assets/4211838/16358186/6d18e178-3ac1-11e6-97c7-1d4e4c8c812f.png)

(v47.0)

**Comment by unhammer** [comment]
![skjermbilete_2016-09-28_13-47-53](https://cloud.githubusercontent.com/assets/56868/18912358/46a78bc8-8582-11e6-907b-2800cbc9331e.png)
I still get this on Firefox 49. As the console shows, the request is received just fine.

**Comment by unhammer** [comment]
A localStorage.clear() and ctrl+shift+R seems to have made it work again. Old localStorage was http://sprunge.us/PAIK. Still no wiser.
