### ISSUE TITLE
language list sometimes goes off edge of screen

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#61]
![screenshot_2016-06-08_165307](https://cloud.githubusercontent.com/assets/963849/15910587/9327468c-2d99-11e6-85f4-130b6e817173.png)

**Comment by sushain97** [comment]
I can't duplicate this. What browser are you using

**Comment by jonorthwash** [comment]
Chromium.  I just tried again on my updated version and I can't reproduce it either.

**Comment by jonorthwash** [comment]
Aha, I can duplicate it.  You have to get it to wrap the languages on the right, and have a narrow browser window size.  Here's one way to do it: use Russian localisation, select Эсперанто (Esperanto) as the source language, let it adjust the languages on the right, then select Датский (Danish) as the source language, let it adjust again (should be wrapped now), and try to select a language on the right.

**Comment by share-with-me** [comment]
+1.
Following are my views on Firefox on decreasing the browser window width.

**dstLangSelectorDropdown**
![screen shot 2017-03-25 at 11 04 16 pm](https://cloud.githubusercontent.com/assets/8894636/24324887/8d47f554-11b4-11e7-85b9-eb3ff3456b74.png)

**srcLangSelectorDropdown**
![screen shot 2017-03-25 at 11 39 49 pm](https://cloud.githubusercontent.com/assets/8894636/24324891/a23c56a8-11b4-11e7-9e63-94c749ebe257.png)

**Comment by share-with-me** [comment]
@jonorthwash @sushain97 I have tried to have solve this by dynamically adjusting the position of dropdown in language selectors based on `window width`. If the width decreases a particular value, these dropdowns shift their positions to fit in the window. I have created a [demo](https://drive.google.com/open?id=0BwrSYlOsMCyWc0l1dkpRVjAxMTg). Please have a look!
Thanks!

**Comment by jonorthwash** [comment]
That looks great! 

Does it adjust the position the selection box will appear if it's not selected when the window is resized?  Does it work based on the static size of the window, or is it only triggered when the window is resized? E.g., the following use case: user opens browser at small size and clicks dropdown, or user makes window smaller and clicks dropdown.

**Comment by share-with-me** [comment]
@jonorthwash  

> That looks great!

Thank you so much :D 
It works in both cases ie even if the user opens it up statically in a narrower width browser window, the dropdown adjusts accordingly. And if he triggers resize, then also depending upon the innerWidth, the dropdown css is applied. I have created a video demonstrating the same.  [Here](https://drive.google.com/open?id=0BwrSYlOsMCyWUWFMNTlRSGk1cW8) is the link!

**Comment by jonorthwash** [comment]
Looks good to me.

**Comment by sushain97** [comment]
@jonorthwash @share-with-me likes to demo with videos before sending the PRs. The videos are really great however having the PR at the same time is nice as well :)

**Comment by share-with-me** [comment]
> Looks good to me, but normally code is demonstrated with PRs and not videos?

Totally agreed :D. I just create a demo video to be sure that my code is indeed proceeding in the correct direction for the issue. 

> @jonorthwash @share-with-me likes to demo with videos before sending the PRs.

:D 

> The videos are really great however having the PR at the same time is nice as well :)

Yes, I am indeed very eager to create new PRs but first I am focusing on the proposal. As soon as I am done with it, I am back on my PR making streak :D.  I will put the draft proposal for you and @jonorthwash  for review. Will await your valuable feedback.

> The fix itself looks promising.

Thank you @sushain97  :D. This means a lot. Will put even more effort to enhance the fix :D
