### ISSUE TITLE
Text sometimes goes off bottom of screen

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#62]
Text sometimes goes off bottom of screen, even when there's plenty of space...
![screenshot_2016-06-08_165307](https://cloud.githubusercontent.com/assets/963849/15910663/ecddf5f4-2d99-11e6-8dd6-9d9d0b24f0e4.png)

**Comment by sushain97** [comment]
This has the same screenshot as #61.

**Comment by jonorthwash** [comment]
Aye, but a different bug.
