### ISSUE TITLE
bad displaying of available languages

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#63]
Not all possible translation languages are displayed in bar of available languages, and unavailable ones are displayed instead.
![screenshot_2016-06-08_170554](https://cloud.githubusercontent.com/assets/963849/15910946/711b2dcc-2d9b-11e6-83f4-291d3325e91e.png)

**Comment by sushain97** [comment]
I don't think that this would be good behavior since it would override the recent destination languages.

**Comment by jonorthwash** [comment]
Should it at least put the default one first?

**Comment by sushain97** [comment]
I think that if there's already one in the recents that is a valid language it picks it and if there isn't any, it boots out the last one and pulls in a new one. I like this behavior since it doesn't shuffle around the UI much. But either way has its advantages...

**Comment by sushain97** [comment]
Closing based on the principle of "not-to-much-shuffling"
