### ISSUE TITLE
language names are sometimes duplicated

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#64]
The languages eng_US and English seem to be differentiated here for no reason:
![screenshot_2016-06-08_183645](https://cloud.githubusercontent.com/assets/963849/15913440/0678b374-2da8-11e6-8495-f5466787b35c.png)

**Comment by sushain97** [comment]
Where is this, i.e. which APY?

**Comment by jonorthwash** [comment]
Hrm, we need to migrate all those SVN tickets to github, no?

**Comment by sushain97** [comment]
Yep... we do.

**Comment by sushain97** [comment]
Moved to #82
