### ISSUE TITLE
dropdown button sometimes disappears

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#65]
The dropdown button for the list of languages on translation input side is sometimes covered by the reverse button:
![screenshot_2016-06-08_183645](https://cloud.githubusercontent.com/assets/963849/15913464/2406133c-2da8-11e6-9109-4509946f9ff5.png)

**Comment by sushain97** [comment]
Having trouble duplicating this one as well. Browser?

**Comment by jonorthwash** [comment]
Chromium.  In order to reproduce, you need to select languages that take up the right amount of space.  Here's another instance of it.
![screenshot_2016-06-25_133939](https://cloud.githubusercontent.com/assets/963849/16358179/4f233aa6-3ada-11e6-9391-f470262d89d9.png)

**Comment by SilentFlame** [comment]
unable to reproduce.

I guess because of small size language names present for English language based browsers.
How can I reproduce the issue?

**Comment by jonorthwash** [comment]
@SilentFlame, you can set the language to Kyrgyz (кыргызча) or Russian (русский) using the localisation dropdown in the top right, as in the examples.  I think you just have to cycle through the various available pairs until it lines up like this.

**Comment by jonorthwash** [comment]
I was just able to reproduce it in firefox by getting long language names all to line up on the right side.
![selection_004](https://cloud.githubusercontent.com/assets/963849/20770337/5bc10e22-b713-11e6-93b0-b2564505b0a2.png)

**Comment by jonorthwash** [comment]
@SilentFlame, it also seems to help to make the browser window narrower, so that it switches to one of the smaller display modes.  Then you don't need such long language names to trigger the issue.

**Comment by share-with-me** [comment]
Yep! I could reproduce this problem on chrome. Narrowing the browser either lets a `language` button overlap the `reverse` button or vice-versa. Following are the screenshots. I plan to solve this issue.

![screen shot 2017-03-26 at 10 10 35 pm](https://cloud.githubusercontent.com/assets/8894636/24333257/61192688-1272-11e7-8f21-8e78e7073b05.png)

![screen shot 2017-03-26 at 10 13 51 pm](https://cloud.githubusercontent.com/assets/8894636/24333259/697b143a-1272-11e7-9c47-c1a6be4ee31b.png)
