### ISSUE TITLE
different languages listed for source/destination

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#66]
![screenshot_2016-06-08_192603](https://cloud.githubusercontent.com/assets/963849/15914450/f555a866-2dae-11e6-9ef0-3f0ddc9c52f6.png)
![screenshot_2016-06-08_192543](https://cloud.githubusercontent.com/assets/963849/15914452/f78106b2-2dae-11e6-82d8-0b7cf7508e0b.png)

**Comment by sushain97** [comment]
Yes? The destination languages are all possible destination languages and the source languages are all possible source languages. They don't have to be equal.

**Comment by jonorthwash** [comment]
Hm, that could be what I was thinking.  In which case, oops!
