### ISSUE TITLE
translation textbox too small when switching from analysis

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#67]
If you load an analysis-only url, such as http://turkic.apertium.org/index.kir.html?choice=kir#analyzation and then click translation, the textboxes come up really small, as in the following screenshot:

![screenshot_2016-07-08_130917](https://cloud.githubusercontent.com/assets/963849/16695341/4729880e-450d-11e6-92cc-d8f50476a79c.png)

When reloading the page, they resize correctly.

**Comment by sushain97** [comment]
@jonorthwash, let me know if it works better now/

**Comment by jonorthwash** [comment]
Seem to be behaving as expected now.  Thanks!
