### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by ftyers** [goavki/apertium-html-tools#76]
I got this email:

<p>Ei Fran,</p>

```
<p>Em diuen que des de Chrome en Android no es pot fer servir
  Apertium.org (foto més avall). Sembla que el desplegable de
  llengua de partida no mostra cap llengua. En saps res?</p>
<p>Gràcies i bon cap de setmana,<br>
  Adrià
```

[ebdiempbhecnpdap.png](https://postimg.org/image/ygt3bf72j/)

**Comment by sushain97** [comment]
I don't think this has anything to do with Android. It works well on my Android device.

**Comment by ftyers** [comment]
Here are the versions:

```
Android 5.0.1
Huawei P8 Lite
```

Maybe it's too old ?

**Comment by sushain97** [comment]
Hm, the Chrome version is what's relevant here.

**Comment by sushain97** [comment]
Closing since there really isn't enough information to fix this.
