### ISSUE TITLE
disentangle js files ("modules")

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#80]
Currently, there's a lot of interdependency in the js files, e.g. localisation depends on stuff from util that depends on stuff from localisation. It'd be nice if the dependencies were hierarchical (no cycles), to make it possible to use e.g. http://flowtype.org/ on the individual files instead of just on the concatenation of the whole project :)

**Comment by Androbin** [comment]
The only real dependency cycle exists between `translator.js` and `util.js`.
First, we should probably figure out where [this block in `util.js`](https://github.com/goavki/apertium-html-tools/blob/master/assets/js/util.js#L82) should go. This code clearly doesn't belong in the utility file.

**Comment by Androbin** [comment]
This would resolve the dependency cycle without further ado. In fact, everything that `util.js` imports from `persistence.js`, `localization.js` and `translator.js` is fully contained within this block.

**Comment by sushain97** [comment]
> First, we should probably figure out where this block in util.js should go. This code clearly doesn't belong in the utility file.

Maybe `init.js`? Any other suggestions?

More importantly, is there a way to prevent this from re-emerging as an issue? Perhaps build flow into the build system?

**Comment by Androbin** [comment]
> More importantly, is there a way to prevent this from re-emerging as an issue? Perhaps build flow into the build system (i.e. CircleCI)?

Maybe we can enforce constraints on which modules may import certain other modules.

**Comment by sushain97** [comment]
> Maybe we can enforce constraints on which modules may import certain other modules.

How? I'd much rather just run Flow... then we get type errors reported as well. (since this task otherwise is literally just copy pasting code, this should get done as well).

**Comment by Androbin** [comment]
Why do only `translator.js` and `util.js` contain the `@flow` annotation?

**Comment by sushain97** [comment]
> Why do only translator.js and util.js contain the @flow annotation?

I dunno. @unhammer did it ;) Presumably, the annotation can be added to all files without actually adding any types yet.

**Comment by unhammer** [comment]
> Why do only `translator.js` and `util.js` contain the `@flow` annotation?

I guess those are the files I worked most on :) Or maybe the other files gave too many errors at the time.

**Comment by Androbin** [comment]
@unhammer So, shall we add the annotation to the other files as well?

**Comment by unhammer** [comment]
Yes, if it doesn't break anything (or if you fix what it breaks ;))

**Comment by Androbin** [comment]
Spoiler: It breaks.

**Comment by sushain97** [comment]
(Flow removed weak mode so now we have to explicitly type a bunch of stuff for it to even start working...)
