### ISSUE TITLE
Inconsistency in the translated view of the page.

### ISSUE THREAD

**Issue by SilentFlame** [goavki/apertium-html-tools#81]
when we change the language to something other than `english` some of the texts on the page gets translated into that language and some does not.
Some texts are in that too random, I mean they do get translated in some and not in some other. 
example: observe the *Mark Unknown words*, *Translate a document*, the sub-heading below "Apertium", seen as below:
![1](https://cloud.githubusercontent.com/assets/9693795/20773069/1fa9b2fa-b776-11e6-954e-4d5e6a1d2914.png)
![2](https://cloud.githubusercontent.com/assets/9693795/20773075/231ed320-b776-11e6-8f2e-97f63baa28b6.png)
![3](https://cloud.githubusercontent.com/assets/9693795/20773077/2511d466-b776-11e6-9f5b-32ba0c8385df.png)

**Comment by sushain97** [comment]
This is not a defect. The behavior is as intended. The translated versions of all strings are not available. What is available is displayed and the English is used otherwise.

**Comment by SilentFlame** [comment]
Oh sorry then. I thought that as an issue or something like that.
