### ISSUE TITLE
Language variant picker

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#82]
Displaying language variants as distinct languages in the translator language selector is awkward and repetitive. Allowing users to first select a language and then display radio buttons for choosing a variant below the relevant translation box, if relevant, provides a better user interface.

The variants would be sorted alphabetically and the first valid option would be selected. Options would continue to be persisted and variant preferences would be stored. If there is only one variant available for a given language, it would be displayed and checked by default.

The proposed implementation would require modification for mobile users since both the language selector and radio buttons would interfere with the flow of the page and not both fit on the same viewport, likely causing confusion. A possible alternative is including the variants as a regular language in the language dropdown for mobile.

**Comment by unhammer** [comment]
How would the workflow be for translating between the variants? Like cat→cat_valencia or whatever

**Comment by sushain97** [comment]
You would select Catalan on both sides and it would default to using a variant on the destination side != the target side. Sound good?

**Comment by unhammer** [comment]
My worry is that the UI turns a bit "undiscoverable" – I certainly wouldn't guess that Apertium could translate into Valencian if I didn't see it in the language list on my first click, so how would I know that I had to select Catalan on both sides to do that? 

One possible solution would be to somehow mark languages-with-variants differently in the (target) language selector, but I can't think of a good way that's both informative and short …

**Comment by sushain97** [comment]
We could have the language selector have a dropdown beside the language name (to indicate variants) but then it's a dropdown within a dropdown...

**Comment by unhammer** [comment]
Hm, what if we do like this:

![variants](https://cloud.githubusercontent.com/assets/56868/21452657/bdc28220-c908-11e6-85cd-b330b3ef6bca.png)

and then when someone clicks "katalansk", it defaults to "cat", but that second selector shows?

**Comment by ryanachi** [comment]
I'm planning on working on this issue next.  Do you think we'll be going ahead with @unhammer 's proposal, or we planning to integrate @sushain97 's 'dropdown-within-dropdown' idea?

**Comment by sushain97** [comment]
@shardulc also has a proposal that we discussed in IRC that could be good. perhaps he can copy the discussion here

**Comment by shardulc** [comment]
On [2017-12-26 on #apertium](https://tinodidriksen.com/pisg/freenode/logs/%23apertium_20171226.log):

```
[05:53:13]
<sushain> we really need to have better variant support :(
<sushain> we’ve needed it for like 4 years
<shardulc> variant = eng_US, cat_valencia, etc. right?
<sushain> yes
<sushain> hbs has three :\
<shardulc> I thought those could be handled just like the other lang names?
<sushain> lol
<sushain> they could be
<sushain> but we decided not to in favor of a better solution
<sushain> and spectie didn’t want to implement a hack
<shardulc> what was the better solution you favored?
<sushain> shardulc: https://github.com/goavki/apertium-html-tools/issues/82
<begiak> [ Language variant picker · Issue #82 · goavki/apertium-html-tools · GitHub ] (posted: 1 year, 3 days ago by sushain)
<shardulc> sushain: what about (image below)
<shardulc> i.e. that interface
<sushain> shardulc: hmmm
<sushain> not that bad
<sushain> I would want Brazilian Standard to be in smaller font
<shardulc> sushain: was just about to say, "with some font and color gimmicks it would be natural" :P
<sushain> heh
<shardulc> so that they're not confusing/unintuitive for other people
<shardulc> sushain: and "Portuguese" would not be clickable
<shardulc> only "Brazilian" and "Standard"
<sushain> hmmm
[06:13:01]
```

![variant picker proposal](https://screenshots.firefoxusercontent.com/images/b82722ea-fd48-4181-a1ee-e930a5d5459c.png)

**Comment by ryanachi** [comment]
Looks good!  @sushain97 If it's OK with you, I'll try to implement the language selection–display as shown on @shardulc 's image, except with a smaller font for the variants.

**Comment by sushain97** [comment]
Yeah, sounds good! Slight modification - nothing about "Standard". Just
variants on new lines with the language name itself also clickable.

**Comment by ryanachi** [comment]
@sushain97 @shardulc how would you like the translator to fetch the name of the variant?  I could create a list of tuples with the language codes and variant names; alternatively, I could just have the translator test for underscores and strip off everything before.  (e.g., 'cat_valencia' --> 'valencia', 'por_BR' --> 'BR')

**Comment by sushain97** [comment]
Variant naming needs to go through langNames.db in APy since the names have
to be available for every language we support. I suggest adding a new SQL
dump file e.g. variants.sql that the Makefile uses when creating
langNames.db.

On Jan 3, 2018 5:49 PM, "ryanachi" <notifications@github.com> wrote:

@sushain97 <https://github.com/sushain97> @shardulc
<https://github.com/shardulc> how would you like the translator to fetch
the name of the variant? I could create a list of tuples with the language
codes and variant names; alternatively, I could just have the translator
test for underscores and strip off everything before. (e.g., 'cat_valencia'
--> 'valencia', 'por_BR' --> 'BR')

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/issues/82#issuecomment-355160308>,
or mute the thread
