### ISSUE TITLE
Website translation

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#83]
This feature has been often requested and used to be present on the old website.

**Comment by unhammer** [comment]
Running in http://gtweb.uit.no/jorgal/ using branch giellatekno of this repo, but several bugs need fixing for this to be considered stable, e.g.

* https://sourceforge.net/p/apertium/tickets/114/ the apertium pipeline needs an overhaul to correctly handle formatting
* https://github.com/goavki/apertium-apy/issues/53 keep pipelines open when translating html pages
* https://github.com/goavki/apertium-apy/issues/52 improve the url cache

**Comment by sushain97** [comment]
some test sites:

![image](https://user-images.githubusercontent.com/4211838/29603772-6ab06fec-87b3-11e7-8bf0-83e771db0cc2.png)

![image](https://user-images.githubusercontent.com/4211838/29603942-ec350262-87b3-11e7-9ea2-a3e5921cb5a0.png)

![image](https://user-images.githubusercontent.com/4211838/29604088-62a9f5a6-87b4-11e7-8544-baa398f9aeb4.png)

![image](https://user-images.githubusercontent.com/4211838/29604111-77a6cc72-87b4-11e7-84f8-3b7c369b4e88.png)

![image](https://user-images.githubusercontent.com/4211838/29604205-c6749212-87b4-11e7-9b9a-f71befdf797f.png)

some also don't work so great so we should follow @jonorthwash's suggestion regarding a "Beta" label.
