### ISSUE TITLE
Initial make curl not found failure should be clearer

### ISSUE THREAD

**Issue by flammie** [goavki/apertium-html-tools#86]
I was trying to install html-tools afterv apy on a new virtual server I got, and it failed with missing curl. This may easily go unnoticed by any user, you should probably consider adding some autotools magic or stuff.

```
$ make

You should edit config.conf

./tools/read-conf.py -c config.conf js > assets/js/config.js
test -d build/js || mkdir -p build/js
touch build/js/.d
echo "config.LOCALES = `cat assets/strings/locales.json`;" > build/js/locales.js
printf "config.PAIRS = " > build/js/listrequests.js
curl -Ss "https://www.apertium.org/apy/list?q=pairs" >> build/js/listrequests.js || ( rm build/js/listrequests.js; false; )
/bin/sh: 1: curl: not found
Makefile:60: recipe for target 'build/js/listrequests.js' failed
make: *** [build/js/listrequests.js] Error 1
```

**Comment by sushain97** [comment]
![image](https://cloud.githubusercontent.com/assets/4211838/21526273/874ffb62-cce8-11e6-83a5-a2276d3baf3d.png)

This is a listed prereq :)

**Comment by unhammer** [comment]
https://github.com/goavki/apertium-html-tools/commit/ab7d3ad51b78c2214d737dba62eab571d2481238 gives 

```
$ sudo mv /usr/bin/curl /usr/bin/curl2
$ make
curl: not found

You need to install curl

Makefile:15: recipe for target 'check-deps' failed
make: *** [check-deps] Error 1

```
– a bit clearer?

**Comment by flammie** [comment]
@unhammer said:
> – a bit clearer?

Yes much better, I think the thing is is you wouldn't of course expect to not have curl either, and the situation of deploying new stuffs is always over minilaptop on the go dodgy internets... thanks. (Like, midori doesn't support quoting on github...)
