### ISSUE TITLE
Chained translation support

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-html-tools#87]
New [features](https://github.com/goavki/apertium-apy/pull/43) added to APy make it possible to chain translations. Html-tools support should function by allowing a configuration flag to enable chained translations. This would make a checkbox appear in the UI, i.e. "Enable translation chaining" or something less jargon-y. Then, the language lists would be modified to have all possible chained pairs. Perhaps we could even color the destination languages based on the number of steps needed with a gradient of some sort, giving somewhat of an understanding of robustness.

**Comment by shardulc** [comment]
I would like to work on this for my [GCI task](https://codein.withgoogle.com/dashboard/task-instances/6369028421451776/).

**Comment by sushain97** [comment]
After #89,

1. Document translation should disable chained translation until this has been implemented APy side (note to self: create an issue for this).
2. x-x translation should not be allowed.
3. Example config needs to have new variable.
4. eng.json should have the new string.
5. Translation not available should be displayed if translation is attempted with a no-longer-possible pair after disabling chaining.
