### ISSUE TITLE
unintrusive notification about installation when we have several timeouts in a row

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#9]
when apertium.org js gets several timeouts in a row, could we have a little notice about "our site seems to be a bit overloaded, you may be interested in learning how to install apertium on your computer"

**Comment by share-with-me** [comment]
For this issue, I measure the load-time for a particular webpage and if it exceeds a threshold, I take the user to a new webpage stating that 'We are busy....'. (screenshot below). I have kept this functionality for each web page so that the user does not have to wait for several timeouts. If load time for any page say increases (5-10 seconds), we display this message. Is my approach correct? Or I should take into account the number of timeouts?
![timedelay](https://cloud.githubusercontent.com/assets/8894636/23830265/b00a3e90-072c-11e7-9497-4126e8398882.png)

**Comment by sushain97** [comment]
@share-with-me this is a great start! I would tackle this issue by checking for a couple of criteria, 1) if any request takes more than X seconds, display the message. 2) If C requests in the last D minutes take more than Y seconds (Y < X), display the message. The message should be unintrusive which means that users should still be able to use the interface. Something similar to how http://bootstrap-notify.remabledesigns.com/ works but there shouldn't be a new dependency added for this issue.

Thanks for the progress update. I appreciate the screenshots.

**Comment by share-with-me** [comment]
@sushain97 Thanks for the feedback. I will have a look at the link and meanwhile also think of tackling the second senario (first being implemented already :P). I will put the screenshots as well. :D

**Comment by share-with-me** [comment]
@sushain97 , I have tried some functionality which shows an error when the site is slow. I have only considered scenario 1 where the issue is displayed in case page takes time to load. Working on scenario 2. Find the [demo link](https://drive.google.com/open?id=0BwrSYlOsMCyWS3NJZjJad3djcDQ)

**Comment by share-with-me** [comment]
@sushain97 for scenario 2 which includes C requests in last D minutes taking Y seconds, what strikes me as a solution is storing the load times of 3 attempts in session variable (or local storage in case we wish to not limit it to only one session) and then calculate the average wait time. If this time exceeds a threshold ( and even if it is < X) , we display the message. Is my approach correct? Or should I consider something else too?

**Comment by sushain97** [comment]
The demo looks good. I have some minor suggestions to make after I try it.

An easier approach is to store the moving average of the last X requests and if it ever goes over Y, display the message. You don't need to do this via local storage or a session, just do it for the current session, i.e. in JS. The status can be lost if the user refreshes.

**Comment by share-with-me** [comment]
@sushain97  Awesome! I will work on the second scenario now. Also, should I create a PR for this at this stage! You can have a look and at the same time suggest the changes. I will update this PR to handle second scenario too and then we can make it mergeable?

**Comment by sushain97** [comment]
Sounds good. Feel free to make a PR at any stage :)

**Comment by share-with-me** [comment]
@sushain97  Awesome! I will do that! one query, what do you mean by 'THe status can be lost if user refreshes'? When a new request is made, page is refreshed right? OR by new request, do we mean the page load time or the amount of time translation or any other service takes? My current understanding is, for the current session ie until user closes the tab/window, I store all the page load times in a session variable and then calculate the average? Am I going wrong about this?

**Comment by share-with-me** [comment]
@sushain97  I have updated my PR (will refactor as per Hound in a while :P) . The functionality is something like, if it takes more than 2 seconds for a page to load, we can see the message. The message has animations such as it fades in and goes out in 10 sec if the user does not interact. He can explicitly choose to close the notice once he has read it with the close button. Lastly, the animation stops on mouse hover and resumes when the mouse is removed.

**Comment by sushain97** [comment]
> My current understanding is, for the current session ie until user closes the tab/window, I store all the page load times in a session variable and then calculate the average?

This is fine. Simple and easy.

> by new request, do we mean the page load time or the amount of time translation or any other service takes?

We don't really care about the page load time. In fact, it's tricky to measure that accurately. What's import is the translation time or any other APy request taking too long.

> The functionality is something like, if it takes more than 2 seconds for a page to load, we can see the message. The message has animations such as it fades in and goes out in 10 sec if the user does not interact.

Both times should be global variables (see the variable section at the top). The behavior sounds perfect! Since we want this behavior to be global across different modes, the variables and notification code probably belongs in `utils.js`.

> He can explicitly choose to close the notice once he has read it with the close button. Lastly, the animation stops on mouse hover and resumes when the mouse is removed.

Perfect. Good work. I'd like some slight UI modifications but we can take care of that at the end.

> will refactor as per Hound in a while

Sounds good. I like to take a look at code after the Hound issues have been fixed. Make sure to rebase/merge master's changes into your branch. It should get rid of some of the `.DS_Store` files etc.

**Comment by share-with-me** [comment]
@sushain97 . That sounds awesome. I will make scripts in utils.js and keep track of the times taken by service to render. The logic of calculating the average remains the same. Is there a readme or guideline book for writing the code that Hound demands, like with all spaces/indentations, functions , naming conventions and newlines etc? that I can follow! It ll help me in writing a good quality code before I even make a PR.

**Comment by sushain97** [comment]
@share-with-me here are Hound's settings for this repo: https://github.com/goavki/apertium-html-tools/blob/master/assets/js/.eslintrc.json

**Comment by share-with-me** [comment]
@sushain97  Thank you so much. I ll hope that my next conforms to these rules. !
