### ISSUE TITLE
Automatically download translated file for Safari, IE, etc.

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#97]
Safari users report documents getting back all garbled

![garble](https://cloud.githubusercontent.com/assets/56868/22023743/c1483408-dcc7-11e6-94f1-7cb4ab095fe1.png)

[tull_test.txt](https://github.com/goavki/apertium-html-tools/files/711250/tull_test.txt)

(moved from https://github.com/goavki/apertium-apy/issues/48 )

**Comment by unhammer** [comment]
We might want to temporarily give Safari users a warning about upgrading to a less [buggy](https://nolanlawson.com/2015/06/30/safari-is-the-new-ie/) browser.

**Comment by sushain97** [comment]
I can confirm this on Safari 9.

I suspect it has something to do with https://github.com/goavki/apertium-html-tools/blob/master/assets/js/translator.js#L644 but I can't find any reliable analysis/solutions from cursory Google searching.

**Comment by unhammer** [comment]
I tried epiphany-browser (which sometimes shares Safari's quirks?), and it also fails. 

Problem 1: we check file.type, which is non-standard: https://developer.mozilla.org/en-US/docs/Web/API/IDBMutableFile/type 
We already check for mime type on the web server (but we show server-mime-failures as "translation not available"!)

Problem 2: I tried using the html "accept" attrib instead: http://sprunge.us/JWDR but epiphany at least sends a file that APY detects as "application/octet-stream" – I don't yet know if that's because the Content-Type of the request is such, or if the file itself differs.

**Comment by sushain97** [comment]
@Problem 1: is it not https://developer.mozilla.org/en-US/docs/Web/API/Blob/type ?

**Comment by unhammer** [comment]
Oh, right. When I log the `droppedFile` in epiphany, it tells me it actually has a `.type`, it's just set to the empty string … I suppose we should allow empty strings, since that at least means the browser hasn't explicitly given a different mime type.

**Comment by unhammer** [comment]
29b009748a0c085c5e770aea6bec70cea4c6224f adds "" as an accepted MIME type js-side (server will, and should, do the real check anyway) and adds accept attribute. Epiphany now lets me drop a document and translate it, but when I click the download link, I don't get an .odt, but it sends me to an address `blob:null/a0594597-30c7-480e-a968-846d140085e0` containing what I suppose is the odt contents:
[blob.txt](https://github.com/goavki/apertium-html-tools/files/720525/blob.txt)

**Comment by unhammer** [comment]
link generated in epiphany: `<a id="fileDownload" href="blob:null/a0594597-30c7-480e-a968-846d140085e0" class="text-center lead" style="" download="Namnlaus 1.odt">`

translator.js code: `$('a#fileDownload')
                                .attr('href', URL.createObjectURL(xhr.response))
                                .attr('download', fileName)`

but http://caniuse.com/#feat=download so Epiphany and Safari don't understand that they should download on clicking that anchor. And in fact, if I right-click and "save target as", it works!

**Comment by sushain97** [comment]
There seem to not be any clean client side remedies for this problem?

**Comment by unhammer** [comment]
piwik for all of 2016 said Safari was 13 % of users and translateDoc was 0.49 % of events (vs translate), ie. we're talking 0.06 % of all events … How about we just give Safari users a little warning that they have to right-click to download the file?

**Comment by sushain97** [comment]
I like the approach. However, adding text = another string to localize... :(

**Comment by unhammer** [comment]
At least it's short?

**Comment by unhammer** [comment]
@sushain97 could you test if https://github.com/goavki/apertium-html-tools/commit/c66767a000ede0c2cb293b0c1c154bb11a8eb7da gives the warning in safari?

**Comment by unhammer** [comment]
That is, drop a doc on http://gtweb.uit.no/jorgal/

**Comment by sushain97** [comment]
The warning shows up:

![image](https://cloud.githubusercontent.com/assets/4211838/22429858/1a67a638-e6da-11e6-82ab-869dcd8cfefb.png)

However, the menu item isn't "Save As". Perhaps something more generic? "either right-click and save/download the filename"?

**Comment by unhammer** [comment]
Epiphany says something like "save link as", so maybe `right-click and save the link with the right filename` (right filename because the user should also write in the extension!

**Comment by sushain97** [comment]
This sounds good. However, I'd like to keep this issue open since there's probably a workaround somewhere out there?

**Comment by unhammer** [comment]
definitely

**Comment by unhammer** [comment]
This might also affect Internet Explorer, according to a user on apertium-contact. It would be nice if someone could verify, but perhaps we should show the warning for IE too since we haven't actually verified that it *does* work on IE :-)

**Comment by myfrom** [comment]
Did anyone try a trick with `<a href="dataURL">`? I can check that method tommorow.

**Comment by myfrom** [comment]
Oh, and BTW: just checked and it doesn't download in IE10 and probably also in Edge13

**Comment by myfrom** [comment]
I was able to fix it for IE10+
If I don't run out of time in GCI task, I'll also try to get Safari done

**Comment by sushain97** [comment]
Since the change for IE was relatively small, I'd like to see this fixed Safari as well. I'm happy to extend the GCI time, not a problem at all.

**Comment by myfrom** [comment]
Thank you. I'll look further into it but I can't guarantee I'll make it.
