### ISSUE TITLE
Website text right-to-left(-ish) if cookies are disabled

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#99]
(Migrated from https://sourceforge.net/p/apertium/tickets/73/, originally reported by David Nemeskey)

I visited the Apertium website with my usual cookie blocker, and found the text is displayed incorrectly. For instance, on the About page, the `<li>` tags display the number on the right side, and are aligned right instead of left; the About button itself is also on the right side. The lower left label reads "!Spotted a mistake? Help us improve Apertium" (and links to the about page instead of e.g. the Sourceforge page, but that is beside the point).

If I enable cookies, the text is displayed correctly. While I expect most "normal" people to have cookies allowed by default, tech savvy people might not, and what they will see if they visit the site is not the best PR.

Firefox 38.0 on Linux Mint 17. I have NoScript installed, but I explicitly allowed scripts for the site.

_Kevin Brubeck Unhammer - 2015-06-21_

What cookie blocker? I tried various settings in Tor Browser, but can't reproduce it. Also, what exact URL was it? (The URL should change based on the language selected.)
     

_David Nemeskey - 2015-06-21_

URL: Just the default one: https://www.apertium.org/#translation. An extension to the bug report: I cannot even select a language without allowing cookies.

I am using Cookie Monster, version 1.2.5.1-signed.

I am attaching two screenshots that show how the site looks on my side.
     
![no_cookie_1](https://cloud.githubusercontent.com/assets/56868/22593249/f7347fb4-ea1d-11e6-8447-bbe910e676fe.png)
![no_cookie_2](https://cloud.githubusercontent.com/assets/56868/22593250/f75570c0-ea1d-11e6-9dab-4ee189a32688.png)

_Kevin Brubeck Unhammer - 2015-06-22_

I just tried adding Cookie Monster to Tor Browser, got the same version in about:addons.

I can't reproduce it with the default Cookie Monster settings, but if I change to "block all cookies" I get something looking like your screenshot. So the user-workaround is to temporarily allow cookies, but it'd be even better if we could fix it on the server :)

Also, my URL changes to https://www.apertium.org/index.eng.html?dir=oci-cat#translation when I load the page with cookies, but not when I block them.

**Comment by share-with-me** [comment]
@unhammer @sushain97 I have attempted a patch to solve this in my [PR](https://github.com/goavki/apertium-html-tools/pull/129).
